package imports

import (
	"archive/zip"
	"context"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/SeriousBug/dowitcher/internal/api"
)

// storedExts are formats that are already compressed. Deflating them again
// burns CPU to make the file marginally bigger.
var storedExts = map[string]bool{
	".avif": true, ".webp": true, ".jpg": true, ".jpeg": true,
}

// padWidth is package.py's `width = max(2, len(str(len(pages))))`: page 1 of 9
// is "01", page 1 of 100 is "001".
func padWidth(pageCount int) int {
	w := len(strconv.Itoa(pageCount))
	if w < 2 {
		w = 2
	}
	return w
}

// comicInfo is the subset of the ComicInfo.xml schema this writes.
//
// package.py writes no metadata at all, leaving a reader to guess the title
// from the filename. Emitting a minimal, valid ComicInfo.xml costs nothing and
// gives internal/cbz something real to parse.
type comicInfo struct {
	XMLName   xml.Name `xml:"ComicInfo"`
	XMLNSXSI  string   `xml:"xmlns:xsi,attr"`
	XMLNSXSD  string   `xml:"xmlns:xsd,attr"`
	Title     string   `xml:"Title,omitempty"`
	PageCount int      `xml:"PageCount"`
	Notes     string   `xml:"Notes,omitempty"`
}

func comicInfoXML(title string, pageCount int) ([]byte, error) {
	ci := comicInfo{
		XMLNSXSI:  "http://www.w3.org/2001/XMLSchema-instance",
		XMLNSXSD:  "http://www.w3.org/2001/XMLSchema",
		Title:     title,
		PageCount: pageCount,
		Notes:     "Generated by Dowitcher.",
	}
	body, err := xml.MarshalIndent(ci, "", "  ")
	if err != nil {
		return nil, err
	}
	return append([]byte(xml.Header), body...), nil
}

// writeCBZ packages pages into a flat zip at outPath.
//
// Entries are named {i:0Nd}{ext}, 1-based, with the extension taken from the
// source file and lowercased. Unlike Python's zipfile there is no archive-level
// default to inherit, so every entry goes through CreateHeader with an explicit
// Method.
func writeCBZ(ctx context.Context, outPath, title string, pages []string, progress ProgressFunc) (int64, error) {
	f, err := os.Create(outPath)
	if err != nil {
		return 0, err
	}
	// A CBZ that failed halfway is worse than none: readers would index it as a
	// real comic. Remove it unless the write runs to completion.
	ok := false
	defer func() {
		f.Close()
		if !ok {
			os.Remove(outPath)
		}
	}()

	zw := zip.NewWriter(f)
	width := padWidth(len(pages))
	progress(api.StagePackaging, 0, len(pages))

	for i, src := range pages {
		if err := ctx.Err(); err != nil {
			return 0, err
		}
		ext := strings.ToLower(filepath.Ext(src))
		method := zip.Deflate
		if storedExts[ext] {
			method = zip.Store
		}
		w, err := zw.CreateHeader(&zip.FileHeader{
			Name:   fmt.Sprintf("%0*d%s", width, i+1, ext),
			Method: method,
		})
		if err != nil {
			return 0, err
		}
		in, err := os.Open(src)
		if err != nil {
			return 0, err
		}
		_, err = io.Copy(w, in)
		in.Close()
		if err != nil {
			return 0, err
		}
		progress(api.StagePackaging, i+1, len(pages))
	}

	ci, err := comicInfoXML(title, len(pages))
	if err != nil {
		return 0, err
	}
	w, err := zw.CreateHeader(&zip.FileHeader{Name: "ComicInfo.xml", Method: zip.Deflate})
	if err != nil {
		return 0, err
	}
	if _, err := w.Write(ci); err != nil {
		return 0, err
	}

	if err := zw.Close(); err != nil {
		return 0, err
	}
	if err := f.Sync(); err != nil {
		return 0, err
	}
	info, err := f.Stat()
	if err != nil {
		return 0, err
	}
	ok = true
	return info.Size(), nil
}

// forceCBZSuffix appends .cbz unless the path already ends in it.
//
// package.py uses Path.with_suffix(".cbz"), which replaces everything after the
// last dot: "On Full Display (avif-q70)" becomes "On Full Display (avif-q70"
// truncated at the dot inside the parentheses. Appending instead keeps names
// that contain dots intact.
func forceCBZSuffix(path string) string {
	if strings.EqualFold(filepath.Ext(path), ".cbz") {
		return path
	}
	return path + ".cbz"
}
