// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds every type that crosses the wire. It is the single source
of truth for the TypeScript client: `go generate ./...` runs tygo over this
package and writes web/src/api/generated.ts. Never hand-edit that file.

Keep internal-only shapes out of this package so they can't leak into the
client. Timestamps are Unix seconds as int64 (tygo maps them to number).
*/

/**
 * APIError is the body of every non-2xx response. The client surfaces .error
 * verbatim, so the text must be safe to show a user.
 */
export interface APIError {
  error: string;
}
/**
 * User is an account. Passkey-only; no password is ever stored.
 */
export interface User {
  id: string;
  name: string;
  isAdmin: boolean;
  createdAt: number /* int64 */;
}
/**
 * Credential is an enrolled passkey, as shown on the account page.
 */
export interface Credential {
  id: string;
  name: string;
  createdAt: number /* int64 */;
  lastUsed?: number /* int64 */;
}
/**
 * Session is the response of GET /auth/me. A logged-out caller gets 401, which
 * the client maps to null rather than an error.
 */
export interface Session {
  user: User;
  credentials: Credential[];
}
/**
 * Invite is a single-use enrollment link. ForUser set means the link enrolls an
 * additional passkey onto an existing account instead of creating one.
 */
export interface Invite {
  token: string;
  createdAt: number /* int64 */;
  expiresAt: number /* int64 */;
  createdBy?: string;
  forUser?: string;
  forUserName?: string;
  isAdmin: boolean;
}
/**
 * Comic is one CBZ in the library.
 * Path is relative to the library root and is the stable identity across
 * rescans: the watcher matches on it first and falls back to content hash so a
 * plain rename keeps reading progress and tags attached.
 */
export interface Comic {
  id: string;
  path: string;
  title: string;
  series?: string;
  number?: string;
  volume?: string;
  summary?: string;
  pageCount: number /* int */;
  fileSize: number /* int64 */;
  addedAt: number /* int64 */;
  modifiedAt: number /* int64 */;
  /**
   * Missing marks a comic whose file vanished. Rows are kept rather than
   * deleted so an unmounted volume doesn't silently destroy tags and
   * progress; the sweep clears the flag if the file comes back.
   */
  missing: boolean;
  tags: string[];
}
/**
 * Page is one image inside a CBZ. Name is the zip entry name.
 */
export interface Page {
  index: number /* int */;
  name: string;
  width?: number /* int */;
  height?: number /* int */;
}
/**
 * ComicDetail is the reader's payload: the comic plus its page list and the
 * caller's own progress.
 */
export interface ComicDetail {
  comic: Comic;
  pages: Page[];
  progress?: Progress;
}
/**
 * Progress is one user's position in one comic. Page is 0-based.
 */
export interface Progress {
  comicId: string;
  page: number /* int */;
  pageCount: number /* int */;
  completed: boolean;
  updatedAt: number /* int64 */;
}
/**
 * Tag is a free-form label. Tags are server-global rather than per-user: a
 * small trusted instance benefits more from everyone seeing the same
 * vocabulary than from per-user namespacing.
 */
export interface Tag {
  name: string;
  count: number /* int */;
}
/**
 * Collection is an ordered, user-owned set of comics.
 */
export interface Collection {
  id: string;
  name: string;
  summary?: string;
  ownerId: string;
  ownerName?: string;
  /**
   * Shared exposes the collection to every other user on the server. Off by
   * default: an uploader opts in per collection, never in bulk.
   */
  shared: boolean;
  count: number /* int */;
  createdAt: number /* int64 */;
  /**
   * CoverComicID is the comic whose cover represents the collection.
   */
  coverComicId?: string;
}
export interface CreateCollectionRequest {
  name: string;
  summary?: string;
  shared: boolean;
}
export interface UpdateCollectionRequest {
  name?: string;
  summary?: string;
  shared?: boolean;
}
export interface SetTagsRequest {
  tags: string[];
}
export interface ProgressRequest {
  page: number /* int */;
  completed: boolean;
}
/**
 * ImportStage names the phase of an import job. The UI shows these verbatim.
 */
export type ImportStage = string;
export const StageUploading: ImportStage = "uploading";
export const StageHashing: ImportStage = "hashing";
export const StageThumbing: ImportStage = "thumbnailing";
export const StageGrouping: ImportStage = "grouping";
export const StageEncoding: ImportStage = "encoding";
export const StagePackaging: ImportStage = "packaging";
export const StageDone: ImportStage = "done";
export const StageFailed: ImportStage = "failed";
/**
 * ImportJob tracks a folder-of-images import through dedupe to a finished CBZ.
 * Jobs are persisted because a large import outlives any one request and must
 * survive a restart well enough to report what happened.
 */
export interface ImportJob {
  id: string;
  name: string;
  ownerId: string;
  stage: ImportStage;
  /**
   * Done/Total drive the progress bar. Total is 0 while it is still unknown.
   */
  done: number /* int */;
  total: number /* int */;
  /**
   * Counts filled in as the pipeline learns them.
   */
  sourceCount: number /* int */;
  pageCount: number /* int */;
  exactDupes: number /* int */;
  nearDupes: number /* int */;
  message?: string;
  comicId?: string;
  startedAt: number /* int64 */;
  finishedAt?: number /* int64 */;
}
/**
 * ImportOptions mirrors package.py's flags. Defaults live in the Go zero value
 * handling, not here, so an omitted field means "server default".
 */
export interface ImportOptions {
  name: string;
  /**
   * Threshold is the mean-absolute-error ceiling for calling two pages the
   * same image, on a 0-255 scale. 3.0 is the empirically derived default:
   * on real galleries duplicate pairs land under ~2.2 and the nearest
   * distinct pair is an order of magnitude above it.
   */
  threshold: number /* float64 */;
  /**
   * Exact skips pixel grouping and dedupes on SHA-256 only.
   */
  exact: boolean;
  /**
   * Encode is "", "avif", "webp" or "jpeg". Empty copies pages verbatim.
   */
  encode?: string;
  quality?: number /* int */;
  /**
   * CollectionID optionally files the finished comic into a collection.
   */
  collectionId?: string;
}
/**
 * DupeGroup is one cluster from the dedupe report: the page that was kept plus
 * the ones it stood in for.
 */
export interface DupeGroup {
  kept: string;
  dropped: string[];
  reason: string;
}
/**
 * LibraryStatus is what the scanner is currently doing.
 */
export interface LibraryStatus {
  scanning: boolean;
  done: number /* int */;
  total: number /* int */;
  lastScan?: number /* int64 */;
  comicCount: number /* int */;
  root: string;
}
/**
 * WSType discriminates a WSMessage. The client switches on it.
 */
export type WSType = string;
export const WSTypeLibrary: WSType = "library";
export const WSTypeComics: WSType = "comics";
export const WSTypeJobs: WSType = "jobs";
export const WSTypeJob: WSType = "job";
/**
 * WSMessage is the push envelope. Payload fields are mutually exclusive
 * pointers so tygo emits them as optional and the client can discriminate on
 * type.
 * Jobs carries the complete job set on connect rather than a delta. That is
 * what lets a reconnecting client clear a spinner for a job the server has
 * since forgotten; without it the spinner outlives the job forever.
 */
export interface WSMessage {
  type: WSType;
  library?: LibraryStatus;
  comics?: Comic[];
  jobs?: ImportJob[];
  job?: ImportJob;
}
