// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds every type that crosses the wire. It is the single source
of truth for the TypeScript client: `go generate ./...` runs tygo over this
package and writes web/src/api/generated.ts. Never hand-edit that file.

Keep internal-only shapes out of this package so they can't leak into the
client. Timestamps are Unix seconds as int64 (tygo maps them to number).
*/

/**
 * APIError is the body of every non-2xx response. The client surfaces .error
 * verbatim, so the text must be safe to show a user.
 */
export interface APIError {
  error: string;
}
/**
 * User is an account. Passkey-only; no password is ever stored.
 */
export interface User {
  id: string;
  name: string;
  isAdmin: boolean;
  createdAt: number /* int64 */;
}
/**
 * Credential is an enrolled passkey, as shown on the account page.
 */
export interface Credential {
  id: string;
  name: string;
  createdAt: number /* int64 */;
  lastUsed?: number /* int64 */;
}
/**
 * Session is the response of GET /auth/me. A logged-out caller gets 401, which
 * the client maps to null rather than an error.
 */
export interface Session {
  user: User;
  credentials: Credential[];
}
/**
 * SignedOutOthers is the response of POST /auth/logout/others. Revoked counts
 * the sessions that were cut, not including the caller's own, which survives.
 */
export interface SignedOutOthers {
  revoked: number /* int64 */;
}
/**
 * Invite is a single-use enrollment link. ForUser set means the link enrolls an
 * additional passkey onto an existing account instead of creating one.
 */
export interface Invite {
  token: string;
  createdAt: number /* int64 */;
  expiresAt: number /* int64 */;
  createdBy?: string;
  forUser?: string;
  forUserName?: string;
  isAdmin: boolean;
}
/**
 * EnrollRequest redeems an invite link. Name is ignored for a recovery invite,
 * which already knows the account it belongs to.
 */
export interface EnrollRequest {
  token: string;
  name: string;
}
/**
 * CreateInviteRequest mints a new-user invite.
 */
export interface CreateInviteRequest {
  isAdmin: boolean;
}
/**
 * APIToken is a scoped credential a user mints for a headless agent (the MCP
 * server). It authenticates as exactly that user and inherits that user's
 * access. The secret is shown once at creation and never stored in plain, so
 * this metadata carries no secret — only what the UI needs to list and revoke.
 */
export interface APIToken {
  id: string;
  name: string;
  createdAt: number /* int64 */;
  /**
   * LastUsed is when the token last authenticated a request, 0 if never.
   */
  lastUsed?: number /* int64 */;
}
/**
 * CreateTokenRequest mints an API token. Name is the user's own label for which
 * agent holds it.
 */
export interface CreateTokenRequest {
  name: string;
}
/**
 * CreateTokenResponse returns a freshly minted token. Secret is the plain token,
 * returned exactly once: the server keeps only its hash, so this is the only
 * moment it can ever be read.
 */
export interface CreateTokenResponse {
  token: APIToken;
  secret: string;
}
/**
 * Comic is one CBZ in the library.
 * Path is relative to the library root and is the stable identity across
 * rescans: the watcher matches on it first and falls back to content hash so a
 * plain rename keeps reading progress and tags attached.
 */
export interface Comic {
  id: string;
  path: string;
  title: string;
  series?: string;
  number?: string;
  volume?: string;
  summary?: string;
  pageCount: number /* int */;
  fileSize: number /* int64 */;
  addedAt: number /* int64 */;
  modifiedAt: number /* int64 */;
  /**
   * Missing marks a comic whose file vanished. Rows are kept rather than
   * deleted so an unmounted volume doesn't silently destroy tags and
   * progress; the sweep clears the flag if the file comes back.
   */
  missing: boolean;
  /**
   * Tags are the caller's own labels on this comic, never anyone else's.
   */
  tags: string[];
  /**
   * Source is where the comic came from: "library", "upload" or "claimed".
   * The client needs it to know which comics an admin may claim, and the
   * reader needs nothing else from it. The owner's id stays server-side.
   */
  source: string;
  /**
   * OwnedByMe reports whether the caller owns this comic — their upload, or a
   * comic they claimed. It answers "may I unclaim this" without naming the
   * owner of a comic the caller does not own.
   */
  ownedByMe: boolean;
}
/**
 * Page is one image inside a CBZ. Name is the zip entry name.
 */
export interface Page {
  index: number /* int */;
  name: string;
  width?: number /* int */;
  height?: number /* int */;
}
/**
 * ComicDetail is the reader's payload: the comic plus its page list and the
 * caller's own progress.
 */
export interface ComicDetail {
  comic: Comic;
  pages: Page[];
  progress?: Progress;
}
/**
 * ComicList is one page of the library.
 * Progress rides alongside the comics rather than inside Comic because it is
 * keyed by comic id and the client joins the two — only the listed comics'
 * progress is included, so the payload stays proportional to the page rather
 * than to the reader's history.
 * Note that a Comic is not server-wide state: its Tags and OwnedByMe are the
 * caller's own, so a rendered list is per-user and must never be broadcast to
 * anyone but the user it was built for. See the warning on WSTypeComics.
 */
export interface ComicList {
  comics: Comic[];
  progress: Progress[];
  /**
   * Total is how many comics match the filter before pagination, which is
   * what the client needs to size the pager.
   */
  total: number /* int */;
  offset: number /* int */;
  limit: number /* int */;
}
/**
 * Progress is one user's position in one comic. Page is 0-based.
 */
export interface Progress {
  comicId: string;
  page: number /* int */;
  pageCount: number /* int */;
  completed: boolean;
  updatedAt: number /* int64 */;
}
/**
 * Tag is a free-form label, private to the user who wrote it. Two users may
 * coin the same name on the same comic and neither sees the other's: a tag is
 * how one reader organises their own shelf, not a shared vocabulary the whole
 * instance edits.
 */
export interface Tag {
  name: string;
  count: number /* int */;
}
/**
 * Collection is an ordered, user-owned set of comics.
 */
export interface Collection {
  id: string;
  name: string;
  summary?: string;
  ownerId: string;
  ownerName?: string;
  /**
   * Shared exposes the collection to every other user on the server. Off by
   * default: an uploader opts in per collection, never in bulk.
   */
  shared: boolean;
  count: number /* int */;
  createdAt: number /* int64 */;
  /**
   * CoverComicID is the comic whose cover represents the collection.
   */
  coverComicId?: string;
}
export interface CreateCollectionRequest {
  name: string;
  summary?: string;
  shared: boolean;
}
export interface UpdateCollectionRequest {
  name?: string;
  summary?: string;
  shared?: boolean;
}
/**
 * CollectionComicRequest names the comic to file into a collection.
 */
export interface CollectionComicRequest {
  comicId: string;
}
/**
 * ReorderCollectionRequest is a collection's whole order, not a move
 * instruction: the full list keeps the stored positions dense and makes the
 * request idempotent, so a retry after a dropped response cannot scramble it.
 */
export interface ReorderCollectionRequest {
  comicIds: string[];
}
export interface SetTagsRequest {
  tags: string[];
}
/**
 * ProgressRequest is a client's claim about where it left off.
 * UpdatedAt is when the client observed the position, not when it managed to
 * send it. An offline client queues writes and replays them on reconnect, so
 * arrival order says nothing about reading order: without a client clock, a
 * phone replaying an hour-old position would clobber the page you are on right
 * now. The server compares it against the stored row and drops the older claim.
 * Zero means the client is not making a claim and the server stamps its own
 * clock, which keeps existing callers working.
 */
export interface ProgressRequest {
  page: number /* int */;
  completed: boolean;
  updatedAt?: number /* int64 */;
}
/**
 * ImportStage names the phase of an import job. The UI shows these verbatim.
 */
export type ImportStage = string;
export const StageUploading: ImportStage = "uploading";
/**
 * StageExtracting is the PDF-only phase where embedded page images are pulled
 * out of the uploaded PDF, before the image pipeline's StageReading runs.
 */
export const StageExtracting: ImportStage = "extracting";
/**
 * StageReading covers one combined pass: each image is read, hashed and
 * thumbnailed in a single decode. The pipeline does not decode twice, so
 * there is no separate thumbnailing stage to report.
 */
export const StageReading: ImportStage = "reading";
export const StageGrouping: ImportStage = "grouping";
export const StageEncoding: ImportStage = "encoding";
export const StagePackaging: ImportStage = "packaging";
export const StageDone: ImportStage = "done";
export const StageFailed: ImportStage = "failed";
/**
 * ImportJob tracks a folder-of-images import through dedupe to a finished CBZ.
 * Jobs are persisted because a large import outlives any one request and must
 * survive a restart well enough to report what happened.
 */
export interface ImportJob {
  id: string;
  name: string;
  ownerId: string;
  stage: ImportStage;
  /**
   * Done/Total drive the progress bar. Total is 0 while it is still unknown.
   */
  done: number /* int */;
  total: number /* int */;
  /**
   * Counts filled in as the pipeline learns them.
   */
  sourceCount: number /* int */;
  pageCount: number /* int */;
  exactDupes: number /* int */;
  nearDupes: number /* int */;
  message?: string;
  comicId?: string;
  startedAt: number /* int64 */;
  finishedAt?: number /* int64 */;
}
/**
 * ImportOptions mirrors package.py's flags. Defaults live in the Go zero value
 * handling, not here, so an omitted field means "server default".
 */
export interface ImportOptions {
  name: string;
  /**
   * Threshold is the mean-absolute-error ceiling for calling two pages the
   * same image, on a 0-255 scale. 3.0 is the empirically derived default:
   * on real galleries duplicate pairs land under ~2.2 and the nearest
   * distinct pair is an order of magnitude above it.
   */
  threshold: number /* float64 */;
  /**
   * Exact skips pixel grouping and dedupes on SHA-256 only.
   */
  exact: boolean;
  /**
   * Encode is "", "avif", "webp" or "jpeg". Empty copies pages verbatim.
   */
  encode?: string;
  quality?: number /* int */;
  /**
   * CollectionID optionally files the finished comic into a collection.
   */
  collectionId?: string;
}
/**
 * DupeGroup is one cluster from the dedupe report: the page that was kept plus
 * the ones it stood in for.
 */
export interface DupeGroup {
  kept: string;
  dropped: string[];
  reason: string;
}
/**
 * LibraryStatus is what the scanner is currently doing.
 */
export interface LibraryStatus {
  scanning: boolean;
  done: number /* int */;
  total: number /* int */;
  lastScan?: number /* int64 */;
  comicCount: number /* int */;
  root: string;
}
/**
 * WSType discriminates a WSMessage. The client switches on it.
 */
export type WSType = string;
/**
 * WSTypeLibrary is scan progress: a property of the server, identical for
 * every user, and the only type the hub's replay cache accepts.
 */
export const WSTypeLibrary: WSType = "library";
/**
 * WSTypeComics is declared but NOTHING PRODUCES IT. Whoever writes that
 * producer, read this first: a comic list is filtered by visibility, so it
 * is per-user by definition. It must go out through Hub.BroadcastTo and
 * never Hub.Broadcast, or one user's library is fanned out to every
 * connected client. It must also never enter the hub's replay cache, which
 * is keyed by message type alone and would hand that payload to whoever
 * connects next. server.cacheable is what enforces the second half.
 */
export const WSTypeComics: WSType = "comics";
/**
 * WSTypeJobs and WSTypeJob are per-user: an import belongs to the user who
 * started it, and its name is the folder they picked, which is usually the
 * sensitive part. Both go out via Hub.BroadcastTo.
 */
export const WSTypeJobs: WSType = "jobs";
export const WSTypeJob: WSType = "job";
/**
 * WSMessage is the push envelope. Payload fields are mutually exclusive
 * pointers so tygo emits them as optional and the client can discriminate on
 * type.
 * Jobs carries the complete job set on connect rather than a delta. That is
 * what lets a reconnecting client clear a spinner for a job the server has
 * since forgotten; without it the spinner outlives the job forever.
 */
export interface WSMessage {
  type: WSType;
  library?: LibraryStatus;
  comics?: Comic[];
  jobs?: ImportJob[];
  job?: ImportJob;
}
